export type ShipperMockOrder = {
  id: string;
  status: "MATCHING" | "DISPATCHED" | "DRIVING" | "DONE";
  isInstantDispatch?: boolean;
  pickupTypeLabel?: string;
  dropoffTypeLabel?: string;
  from: string;
  to: string;
  distanceKm: number;
  cargoSummary: string;
  loadMethodShort: string;
  workToolShort: string;
  priceWon: number;
  updatedAtLabel: string;
  updatedAtMs?: number;
  pickupTimeHHmm?: string;
  dropoffTimeHHmm?: string;
};

export const MOCK_SHIPPER_ORDERS: ShipperMockOrder[] = [
  {
    id: "m1",
    status: "MATCHING",
    from: "서울 강남",
    to: "부산 해운대",
    distanceKm: 340,
    cargoSummary: "11톤 윙바디",
    loadMethodShort: "독",
    workToolShort: "지",
    priceWon: 350000,
    updatedAtLabel: "10분 전",
  },
  {
    id: "m2",
    status: "DRIVING",
    from: "서울 구로",
    to: "경기 화성",
    distanceKm: 62,
    cargoSummary: "3.5톤 카고",
    loadMethodShort: "혼",
    workToolShort: "수",
    priceWon: 180000,
    updatedAtLabel: "오늘 10:00 상차",
  },
  {
    id: "m3",
    status: "DISPATCHED",
    isInstantDispatch: true,
    from: "인천 남동",
    to: "대전 유성",
    distanceKm: 120,
    cargoSummary: "5톤 카고",
    loadMethodShort: "독",
    workToolShort: "크",
    priceWon: 210000,
    updatedAtLabel: "오늘 14:00 상차",
  },
  {
    id: "m4",
    status: "DRIVING",
    from: "서울 영등포",
    to: "경기 수원",
    distanceKm: 45,
    cargoSummary: "1톤 용달",
    loadMethodShort: "혼",
    workToolShort: "호",
    priceWon: 80000,
    updatedAtLabel: "오늘 09:00 상차",
  },
  {
    id: "m5",
    status: "DRIVING",
    from: "경기 평택",
    to: "충북 청주",
    distanceKm: 98,
    cargoSummary: "5톤 윙바디",
    loadMethodShort: "독",
    workToolShort: "지",
    priceWon: 190000,
    updatedAtLabel: "오늘 08:30 상차",
  },
  {
    id: "m6",
    status: "DONE",
    from: "대구 달서구",
    to: "경북 구미시",
    distanceKm: 34,
    cargoSummary: "2.5톤 카고",
    loadMethodShort: "혼",
    workToolShort: "수",
    priceWon: 90000,
    updatedAtLabel: "3일 전 완료",
  },
  {
    id: "m7",
    status: "MATCHING",
    from: "광주 광산구",
    to: "전북 전주시",
    distanceKm: 92,
    cargoSummary: "5톤 카고",
    loadMethodShort: "독",
    workToolShort: "지",
    priceWon: 175000,
    updatedAtLabel: "5분 전",
  },
  {
    id: "m8",
    status: "DRIVING",
    from: "울산 남구",
    to: "경남 창원시",
    distanceKm: 54,
    cargoSummary: "3.5톤 윙바디",
    loadMethodShort: "혼",
    workToolShort: "수",
    priceWon: 120000,
    updatedAtLabel: "오늘 16:30 상차",
  },
  {
    id: "m9",
    status: "DRIVING",
    from: "충남 아산시",
    to: "대전 유성구",
    distanceKm: 41,
    cargoSummary: "1톤 용달",
    loadMethodShort: "독",
    workToolShort: "호",
    priceWon: 78000,
    updatedAtLabel: "오늘 08:00 상차",
  },
  {
    id: "m10",
    status: "DONE",
    from: "서울 금천구",
    to: "인천 연수구",
    distanceKm: 38,
    cargoSummary: "2.5톤 카고",
    loadMethodShort: "혼",
    workToolShort: "크",
    priceWon: 98000,
    updatedAtLabel: "어제 완료",
  },
  {
    id: "m11",
    status: "DRIVING",
    isInstantDispatch: true,
    from: "경기 고양시",
    to: "강원 원주시",
    distanceKm: 114,
    cargoSummary: "11톤 윙바디",
    loadMethodShort: "독",
    workToolShort: "지",
    priceWon: 265000,
    updatedAtLabel: "오늘 11:00 상차",
  },
  {
    id: "m12",
    status: "DONE",
    from: "부산 사상구",
    to: "경남 김해시",
    distanceKm: 19,
    cargoSummary: "1톤 탑차",
    loadMethodShort: "혼",
    workToolShort: "수",
    priceWon: 52000,
    updatedAtLabel: "5일 전 완료",
  },
  {
    id: "m13",
    status: "DRIVING",
    from: "경북 포항시",
    to: "대구 북구",
    distanceKm: 89,
    cargoSummary: "5톤 냉장",
    loadMethodShort: "독",
    workToolShort: "크",
    priceWon: 168000,
    updatedAtLabel: "오늘 07:30 상차",
  },
];
