import { StyleSheet } from "react-native";

import { SP } from "./createOrderStep1.constants";

export const s = StyleSheet.create({
  page: { flex: 1 },

  topBar: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SP.pageX,
    borderBottomWidth: 1,
  },
  backBtn: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  topTitle: { fontSize: 16, fontWeight: "900" },
  content: { padding: SP.pageX, paddingBottom: 24 },

  sectionTitle: { fontSize: 16, fontWeight: "900", marginBottom: 10 },
  fieldLabel: { fontSize: 13, fontWeight: "800", marginBottom: 8 },

  timelineRow: { flexDirection: "row" },
  timelineLeft: { width: 52, alignItems: "center" },
  circle: { width: 34, height: 34, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  circleText: { fontSize: 11, fontWeight: "900" },
  lineV: { width: 2, flex: 1, marginTop: 8 },
  timelineBody: { flex: 1 },

  select: {
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  selectText: { fontSize: 14, fontWeight: "700", flex: 1 },

  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: SP.chipGap, marginTop: 10 },
  chip: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    maxWidth: "100%",
  },
  chipText: { fontSize: 12, fontWeight: "900" },
  dateRow: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 12,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dateLabelRow: { flexDirection: "row", alignItems: "center", gap: 6, flex: 1 },
  dateValueText: { fontSize: 13, fontWeight: "800" },

  searchField: {
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: { flex: 1, fontSize: 14, fontWeight: "700" },

  dropdownPanel: {
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 8,
  },
  dropdownSearchWrap: {
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dropdownSearchInput: { flex: 1, fontSize: 13, fontWeight: "700" },
  dropdownList: {},
  dropdownListScrollable: { maxHeight: 180 },
  dropdownItem: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  dropdownItemText: { flex: 1, fontSize: 13, fontWeight: "800", marginRight: 8 },
  dropdownEmptyText: { fontSize: 12, fontWeight: "700", paddingVertical: 10 },

  addressSuggestWrap: {
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 12,
    overflow: "hidden",
  },
  addressSuggestItem: {
    minHeight: 40,
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  addressSuggestText: { flex: 1, fontSize: 13, fontWeight: "700" },

  twoSelectRow: { flexDirection: "row" },

  twoCol: { flexDirection: "row" },
  inputWrap: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, height: 48, justifyContent: "center" },
  input: { fontSize: 14, fontWeight: "700" },
  inputWrapMulti: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, minHeight: 110 },
  inputMulti: { fontSize: 14, fontWeight: "700", height: 110, textAlignVertical: "top" },

  tagWrap: { flexDirection: "row", flexWrap: "wrap", gap: SP.chipGap },

  photoRow: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 10 },
  photoBox: {
    width: "48%",
    height: 86,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
  },
  photoText: { fontSize: 12, fontWeight: "900" },
  photoHint: { fontSize: 10, fontWeight: "800" },

  choiceRow: { flexDirection: "row", gap: 12, marginTop: 10 },
  choiceCard: { flex: 1, borderRadius: 16, borderWidth: 1, padding: 14 },
  emoji: { fontSize: 18, marginBottom: 8 },
  choiceTitle: { fontSize: 14, fontWeight: "900", marginBottom: 6 },
  choiceDesc: { fontSize: 12, fontWeight: "700", lineHeight: 16 },

  aiBox: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
  },
  tripHeaderRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  tripHeaderLabel: { fontSize: 14, fontWeight: "900" },
  tripPillRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  tripPill: {
    minWidth: 50,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tripPillText: { fontSize: 12, fontWeight: "800" },
  tripPillTextActive: { fontWeight: "900" },
  aiBottomRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 },
  aiTextWrap: { flex: 1, paddingTop: 2 },
  aiLabel: { fontSize: 12, fontWeight: "900", lineHeight: 18, marginBottom: 4 },
  aiPrice: { fontSize: 22, fontWeight: "900", lineHeight: 26 },

  fareRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  fareInputWrap: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  wonSuffix: { fontSize: 13, fontWeight: "900" },
  hint: { marginTop: 8, fontSize: 12, fontWeight: "800" },

  payGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 10 },
  payTile: { width: "48%", borderRadius: 16, borderWidth: 1, padding: 14 },
  payTitle: { fontSize: 14, fontWeight: "900", marginBottom: 6 },
  payDesc: { fontSize: 12, fontWeight: "700" },

  feeRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 8 },
  feeLabel: { fontSize: 12, fontWeight: "800" },
  feeValue: { fontSize: 12, fontWeight: "900" },
  hr: { height: 1, marginTop: 12 },
  feeTotalLabel: { fontSize: 14, fontWeight: "900", marginTop: 10 },
  feeTotalValue: { fontSize: 14, fontWeight: "900", marginTop: 10 },

  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: SP.pageX,
    borderTopWidth: 1,
    gap: 10,
  },
  stickySummary: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  stickyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  stickyLabel: { fontSize: 12, fontWeight: "900" },
  stickyTotal: { fontSize: 18, fontWeight: "900" },
  stickySubRow: { marginTop: 6, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  stickySub: { fontSize: 12, fontWeight: "800" },
});
