import { OrderResponse } from "./models/order";

export const MOCK_ORDERS: OrderResponse[] = [
  {
    orderId: 101,
    status: "REQUESTED",
    instant: true,
    createdAt: "2026-02-12T14:00:00Z",
    startAddr: "경기 수원시 영통구 매탄동 123",
    startPlace: "삼성전자 물류센터 A동",
    startType: "당상",
    startSchedule: "오늘 14:00",
    endAddr: "부산 강서구 대저동 456",
    endPlace: "강서 유통단지 3물류",
    endType: "당착",
    endSchedule: "오늘 19:30",
    cargoContent: "정밀 전자부품 (파레트)",
    loadMethod: "독차",
    workType: "지게차",
    tonnage: 11,
    reqCarType: "윙바디",
    reqTonnage: "11톤",
    driveMode: "편도",
    loadWeight: 8500,
    basePrice: 420000,
    laborFee: 0,
    packagingPrice: 0,
    insuranceFee: 15000,
    payMethod: "인수증/후불",
    distance: 340,
    duration: 18000,
    remark: "충격 주의 화물입니다. 결박 꼼꼼히 확인 부탁드립니다.",
    user: {
      userId: 1,
      nickname: "광교물류",
      phone: "010-1234-5678",
      email: "gg_logis@example.com",
      ratingAvg: 4.8,
      role: "SHIPPER",
    },
  },
  {
    orderId: 102,
    status: "REQUESTED",
    instant: false,
    createdAt: "2026-02-12T13:30:00Z",
    startAddr: "서울 강동구 상일동 789",
    startPlace: "쿠팡 신선센터 2층",
    startType: "익상",
    startSchedule: "내일 09:00",
    endAddr: "강원 원주시 지정면 321",
    endPlace: "지정면 물류창고",
    endType: "내착",
    endSchedule: "내일 11:30",
    cargoContent: "냉동 식품 (박스)",
    loadMethod: "혼적",
    workType: "수작업",
    tonnage: 1,
    reqCarType: "카고",
    reqTonnage: "1톤",
    driveMode: "왕복",
    loadWeight: 800,
    basePrice: 150000,
    laborFee: 30000,
    packagingPrice: 5000,
    insuranceFee: 0,
    payMethod: "현금/선불",
    distance: 85,
    duration: 5400,
    remark: "상차 시 수작업 도움이 필요합니다. 상의 후 진행 바랍니다.",
    user: {
      userId: 2,
      nickname: "원주신선",
      phone: "010-9876-5432",
      email: "fresh_wj@example.com",
      ratingAvg: 4.5,
      role: "SHIPPER",
    },
  },
  {
    orderId: 103,
    status: "ACCEPTED",
    instant: true,
    createdAt: "2026-02-12T15:20:00Z",
    startAddr: "인천 서구 가좌동 555",
    startPlace: "인천항 제3부두",
    startType: "당상",
    startSchedule: "오늘 17:00",
    endAddr: "충남 천안시 서북구",
    endPlace: "천안 공장",
    endType: "당착",
    endSchedule: "오늘 19:00",
    cargoContent: "수입 가구",
    loadMethod: "독차",
    workType: "지게차",
    tonnage: 5,
    reqCarType: "윙바디",
    reqTonnage: "5톤",
    driveMode: "편도",
    loadWeight: 4500,
    basePrice: 250000,
    laborFee: 0,
    packagingPrice: 10000,
    insuranceFee: 15000,
    payMethod: "인수증/후불",
    distance: 110,
    duration: 7200,
    remark: "가구가 손상되지 않게 깔판 필수입니다.",
    user: {
      userId: 3,
      nickname: "인천가구",
      phone: "010-5555-4444",
      email: "ic_f@example.com",
      ratingAvg: 4.9,
      role: "SHIPPER",
    },
  },
  {
    orderId: 104,
    status: "REQUESTED",
    instant: false,
    createdAt: "2026-02-12T16:00:00Z",
    startAddr: "경북 구미시 산동읍",
    startPlace: "구미 국가산단 4단지",
    startType: "당상",
    startSchedule: "오늘 18:00",
    endAddr: "경기 안산시 단원구",
    endPlace: "시화공단 2나동",
    endType: "내착",
    endSchedule: "내일 08:30",
    cargoContent: "금형 틀 (중량물)",
    loadMethod: "독차",
    workType: "크레인",
    tonnage: 25,
    reqCarType: "평카고",
    reqTonnage: "25톤",
    driveMode: "편도",
    loadWeight: 22000,
    basePrice: 550000,
    laborFee: 0,
    packagingPrice: 0,
    insuranceFee: 50000,
    payMethod: "인수증/후불",
    distance: 210,
    duration: 12000,
    remark: "야간 주행 시 과속 금지, 크레인 상차 대기 있을 수 있음.",
    user: {
      userId: 4,
      nickname: "구미엔지니어링",
      phone: "010-1111-2222",
      email: "gumi_en@example.com",
      ratingAvg: 4.7,
      role: "SHIPPER",
    },
  },
  {
    orderId: 105,
    status: "ACCEPTED",
    instant: true,
    createdAt: "2026-02-12T10:00:00Z",
    startAddr: "충북 청주시 흥덕구",
    startPlace: "청주 산단 물류팀",
    startType: "당상",
    startSchedule: "오늘 13:00",
    endAddr: "전남 광양시 광양항",
    endPlace: "광양 컨테이너 부두",
    endType: "당착",
    endSchedule: "오늘 17:00",
    cargoContent: "수출용 배터리",
    loadMethod: "독차",
    workType: "지게차",
    tonnage: 5,
    reqCarType: "윙바디",
    reqTonnage: "5톤",
    driveMode: "편도",
    loadWeight: 3500,
    basePrice: 320000,
    laborFee: 0,
    packagingPrice: 0,
    insuranceFee: 30000,
    payMethod: "인수증/후불",
    distance: 245,
    duration: 14400,
    remark: "위험물 교육 이수 기사님 선호합니다. 화기 엄금.",
    user: {
      userId: 5,
      nickname: "청주에너지",
      phone: "010-3333-5555",
      email: "cj_energy@example.com",
      ratingAvg: 4.6,
      role: "SHIPPER",
    },
  },
  {
    orderId: 106,
    status: "REQUESTED",
    instant: false,
    createdAt: "2026-02-12T09:15:00Z",
    startAddr: "전북 익산시 팔봉동",
    startPlace: "익산 제2공단 본관",
    startType: "익상",
    startSchedule: "내일 10:00",
    endAddr: "서울 금천구 가산동",
    endPlace: "가산 IT 타워 1차",
    endType: "내착",
    endSchedule: "내일 14:00",
    cargoContent: "의류 샘플 박스",
    loadMethod: "혼적",
    workType: "수작업",
    tonnage: 2.5,
    reqCarType: "카고",
    reqTonnage: "2.5톤",
    driveMode: "편도",
    loadWeight: 1200,
    basePrice: 190000,
    laborFee: 20000,
    packagingPrice: 0,
    insuranceFee: 0,
    payMethod: "현금/선불",
    distance: 205,
    duration: 10800,
    remark: "박스 수량이 많습니다. 상차 시 도와드려요.",
    user: {
      userId: 6,
      nickname: "익산패션",
      phone: "010-6666-7777",
      email: "is_fashion@example.com",
      ratingAvg: 4.4,
      role: "SHIPPER",
    },
  },
  {
    orderId: 107,
    status: "REQUESTED",
    instant: true,
    createdAt: "2026-02-12T11:45:00Z",
    startAddr: "강원 강릉시 주문진읍",
    startPlace: "주문진 수산시장 뒷편",
    startType: "당상",
    startSchedule: "오늘 16:00",
    endAddr: "경기 하남시 풍산동",
    endPlace: "하남 수산물 복합단지",
    endType: "당착",
    endSchedule: "오늘 19:00",
    cargoContent: "활어 (수족관차)",
    loadMethod: "독차",
    workType: "지게차",
    tonnage: 3.5,
    reqCarType: "냉동탑",
    reqTonnage: "3.5톤",
    driveMode: "편도",
    loadWeight: 2500,
    basePrice: 280000,
    laborFee: 0,
    packagingPrice: 20000,
    insuranceFee: 0,
    payMethod: "현금/선불",
    distance: 180,
    duration: 9000,
    remark: "수온 유지 필수, 도착 후 즉시 하차 요청.",
    user: {
      userId: 7,
      nickname: "주문진수산",
      phone: "010-8888-9999",
      email: "fish_kj@example.com",
      ratingAvg: 4.9,
      role: "SHIPPER",
    },
  },
  {
    orderId: 108,
    status: "IN_TRANSIT",
    instant: false,
    createdAt: "2026-02-12T08:00:00Z",
    startAddr: "충남 당진시 송악읍",
    startPlace: "현대제철 인근 창고",
    startType: "당상",
    startSchedule: "오늘 11:00",
    endAddr: "경기 평택시 포승읍",
    endPlace: "평택항 자유무역지역",
    endType: "당착",
    endSchedule: "오늘 12:30",
    cargoContent: "철강 코일",
    loadMethod: "독차",
    workType: "크레인",
    tonnage: 11,
    reqCarType: "카고",
    reqTonnage: "11톤",
    driveMode: "왕복",
    loadWeight: 10000,
    basePrice: 120000,
    laborFee: 0,
    packagingPrice: 0,
    insuranceFee: 10000,
    payMethod: "인수증/후불",
    distance: 35,
    duration: 3600,
    remark: "단거리 왕복 오더입니다. 고임목 필수 지참.",
    user: {
      userId: 8,
      nickname: "당진스틸",
      phone: "010-2222-3333",
      email: "dj_steel@example.com",
      ratingAvg: 4.3,
      role: "SHIPPER",
    },
  },
  {
    orderId: 109,
    status: "COMPLETED",
    instant: true,
    createdAt: "2026-02-12T17:30:00Z",
    startAddr: "대전 대덕구 문평동",
    startPlace: "대전 3공단 입구",
    startType: "야간상차",
    startSchedule: "오늘 22:00",
    endAddr: "경남 함안군 칠서면",
    endPlace: "칠서 지방산단",
    endType: "내착",
    endSchedule: "내일 07:00",
    cargoContent: "자동차 부품",
    loadMethod: "독차",
    workType: "지게차",
    tonnage: 5,
    reqCarType: "윙바디",
    reqTonnage: "5톤",
    driveMode: "편도",
    loadWeight: 4000,
    basePrice: 380000,
    laborFee: 0,
    packagingPrice: 0,
    insuranceFee: 5000,
    payMethod: "인수증/후불",
    distance: 200,
    duration: 10800,
    remark: "야간 주행 오더입니다. 졸음 운전 주의 부탁드려요.",
    user: {
      userId: 9,
      nickname: "대전테크",
      phone: "010-4444-6666",
      email: "dj_tech@example.com",
      ratingAvg: 4.7,
      role: "SHIPPER",
    },
  },
  {
    orderId: 110,
    status: "REQUESTED",
    instant: false,
    createdAt: "2026-02-12T13:00:00Z",
    startAddr: "서울 마포구 상암동",
    startPlace: "방송센터 지하 주차장",
    startType: "당상",
    startSchedule: "오늘 15:00",
    endAddr: "제주 제주시 해안동",
    endPlace: "제주 로케이션 창고",
    endType: "내착",
    endSchedule: "모레 10:00",
    cargoContent: "방송 촬영 장비",
    loadMethod: "독차",
    workType: "수작업",
    tonnage: 5,
    reqCarType: "윙바디",
    reqTonnage: "5톤",
    driveMode: "편도",
    loadWeight: 3000,
    basePrice: 950000,
    laborFee: 100000,
    packagingPrice: 50000,
    insuranceFee: 100000,
    payMethod: "현금/선불",
    distance: 450,
    duration: 86400,
    remark: "제주도 배편 포함 금액입니다. 장비 파손 주의 요망.",
    user: {
      userId: 10,
      nickname: "상암미디어",
      phone: "010-7777-8888",
      email: "sa_media@example.com",
      ratingAvg: 5.0,
      role: "SHIPPER",
    },
  },
];
