import { StyleSheet } from "react-native";

export const orderCardStyles = StyleSheet.create({
  container: {
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 12,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  badgeRow: { flexDirection: "row", alignItems: "center" },
  timeText: { fontSize: 12, color: "#94A3B8" },
  routeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  locGroup: { flex: 1.5 },
  locLabel: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
    marginBottom: 4,
  },
  locName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1E293B",
    letterSpacing: -0.5,
  },
  placeText: { fontSize: 12, color: "#94A3B8", marginTop: 2 },
  arrowArea: { flex: 1, alignItems: "center", paddingHorizontal: 8 },
  distBadge: {
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 99,
    marginBottom: 4,
  },
  distText: { fontSize: 11, fontWeight: "700", color: "#475569" },
  line: {
    width: "100%",
    height: 2,
    backgroundColor: "#F1F5F9",
    position: "relative",
  },
  arrowHead: {
    position: "absolute",
    right: 0,
    top: -3,
    width: 7,
    height: 7,
    borderTopWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: "#CBD5E1",
    transform: [{ rotate: "45deg" }],
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  infoColumn: { flex: 1.5 },
  loadDateText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
    marginBottom: 2,
  },
  carText: { fontSize: 14, fontWeight: "700", color: "#334155" },
  priceColumn: { flex: 1.2, alignItems: "flex-end" },
  priceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "flex-end",
  },
  priceText: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1E293B",
    letterSpacing: -0.5,
  },
  taxLabel: {
    fontSize: 12,
    color: "#EF4444",
    fontWeight: "800",
    marginLeft: 4,
  },
});
