import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 15,
  },
  headerBtn: { padding: 8 },
  headerTitle: { fontSize: 16, fontWeight: "800" },
  statusHeader: { margin: 16, marginBottom: 0, padding: 14, borderRadius: 16 },
  statusHeaderRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  statusHeaderText: { fontSize: 14, fontWeight: "700", flex: 1 },
  scrollContent: { padding: 16 },
  card: { borderRadius: 24, padding: 20, marginBottom: 16 },
  sectionCard: { borderRadius: 24, padding: 20, marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "800", marginBottom: 16 },
  routeMiniCard: {
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    overflow: "hidden",
  },
  routeMiniHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  routeMiniTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  routeMiniExpandBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderRadius: 8,
  },
  routeMiniExpandText: {
    fontSize: 12,
    fontWeight: "600",
    marginLeft: 4,
  },
  routeMiniMapWrap: {
    height: 180,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  routeMiniMapWebview: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  routeMiniEmpty: {
    height: 120,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
  },
  routeMiniEmptyText: {
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  routeMiniErrorText: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "700",
    color: "#B91C1C",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  badgeGroup: { flexDirection: "row", gap: 6, flexWrap: "wrap", flex: 1 },
  unifiedBadge: { alignItems: "center" },
  dateText: { fontSize: 12 },
  routeBigRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  addrBox: { flex: 1 },
  addrBig: { fontSize: 22, fontWeight: "900", letterSpacing: -0.5 },
  addrSmall: { fontSize: 14, marginTop: 2 },
  infoBar: {
    flexDirection: "row",
    padding: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  infoItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  divider: { width: 1, height: 12, marginHorizontal: 16 },
  infoText: { fontSize: 13, fontWeight: "700" },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 18,
    borderTopWidth: 1,
  },
  priceLabel: { fontSize: 14, fontWeight: "600" },
  priceRight: { flexDirection: "row", alignItems: "center" },
  priceValue: { fontSize: 24, fontWeight: "900" },
  timelineContainer: { position: "relative" },
  timelineLine: {
    position: "absolute",
    left: 14,
    top: 24,
    bottom: 24,
    width: 2,
  },
  timelineItem: { flexDirection: "row", gap: 16 },
  timelineDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  dotText: { fontSize: 12, fontWeight: "900", color: "#FFF" },
  timelineContent: { flex: 1 },
  timeLabel: { fontSize: 13, fontWeight: "800", marginBottom: 4 },
  placeTitle: { fontSize: 16, fontWeight: "800" },
  placeDetail: { fontSize: 13, marginTop: 2 },
  routePreviewWrap: {
    flex: 1,
  },
  routePreviewHeader: {
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  routePreviewTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  routePreviewBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  routePreviewHeaderPlaceholder: {
    width: 40,
    height: 40,
  },
  routePreviewBody: {
    flex: 1,
  },
  routePreviewErrorBox: {
    marginHorizontal: 12,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
    borderWidth: 1,
    zIndex: 10,
  },
  routePreviewErrorText: {
    color: "#991B1B",
    fontSize: 12,
    fontWeight: "700",
  },
  routePreviewWebview: {
    flex: 1,
    backgroundColor: "#fff",
  },
  routePreviewEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  gridContainer: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  gridItem: { width: (width - 82) / 2, padding: 16, borderRadius: 16 },
  gridLabel: { fontSize: 12, marginBottom: 6, fontWeight: "600" },
  gridValue: { fontSize: 15, fontWeight: "800" },
  gridSubValue: { fontSize: 12, marginTop: 4, fontWeight: "600" },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    paddingHorizontal: 16,
    paddingTop: 12,
    flexDirection: "row",
    gap: 12,
    borderTopWidth: 1,
  },
  iconBtnGroup: { flexDirection: "row", gap: 10 },
  circleBtn: {
    width: 54,
    height: 54,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  mainActionBtn: {
    flex: 1,
    height: 54,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  btnContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  mainActionText: { color: "#FFF", fontSize: 17, fontWeight: "800" },
  managerBox: { padding: 16, borderRadius: 12, borderWidth: 1, gap: 12 },
  managerRow: { flexDirection: "row", alignItems: "center" },
  managerLabel: { fontSize: 14, width: 60, marginLeft: 8, fontWeight: "700" },
  managerValue: { fontSize: 15, fontWeight: "800", flex: 1 },
  memoBox: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 80, // 내용이 짧아도 어느 정도 영역을 확보해서 눈에 띄게 함
  },
  memoText: {
    fontSize: 15,
    lineHeight: 22, // 줄 간격을 넓혀서 긴 글도 읽기 편하게 함
    fontWeight: "600", // 내용을 좀 더 두껍게 해서 강조
  },
  requestTagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  requestTagChip: {
    backgroundColor: "#FEF3C7",
    borderWidth: 1,
    borderColor: "#FCD34D",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  requestTagText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#92400E",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.35)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    borderRadius: 16,
    padding: 16,
    maxHeight: "70%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewLabel: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 8,
  },
  starRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  starBtn: {
    marginRight: 8,
  },
  reportTypeWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  reportTypeChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reviewInput: {
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 100,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: "top",
    marginBottom: 14,
    fontSize: 14,
  },
  reviewSubmitBtn: {
    height: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewSubmitText: {
    color: "#FFF",
    fontSize: 15,
    fontWeight: "800",
  },
  breakdownContainer: {
    paddingTop: 12,
    paddingBottom: 4,
  },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 14,
  },
  breakdownValue: {
    fontSize: 14,
  },
  payMethodRow: {
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
  },
  payMethodHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  payMethodText: {
    fontSize: 13,
    lineHeight: 18,
  },
});
